version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8
          name: Run linter
      - run:
          command: mypy algorithms
          name: Run type checker
      - run:
          command: pytest
          name: Run tests

workflows:
  main:
    jobs:
      - build-and-test
